# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2019-01-25 04:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PictureInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pcreatetime', models.DateTimeField()),
                ('purl', models.CharField(max_length=100)),
                ('pstatus', models.CharField(max_length=1)),
                ('pretime', models.FloatField()),
                ('preresult', models.CharField(max_length=1)),
                ('prepercent_0', models.FloatField()),
                ('prepercent_1', models.FloatField()),
                ('prepercent_2', models.FloatField()),
                ('prepercent_3', models.FloatField()),
                ('prepercent_4', models.FloatField()),
                ('prepercent_5', models.FloatField()),
                ('prepercent_6', models.FloatField()),
                ('prepercent_7', models.FloatField()),
                ('prepercent_8', models.FloatField()),
                ('prepercent_9', models.FloatField()),
                ('puser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.UserInfo')),
            ],
        ),
    ]
